### PR TITLE
PR: Downgrade plug version for phoenix compatibility issue #76

### LINKED ISSUE #82: warning: `Application.get_env/2` discouraged use `Application.compile_env/3` instead
Getting the following error in a downstream project that is using `auth_plug`: https://github.com/dwyl/phoenix-chat-example/pull/120
```
warning: Application.get_env/2 is discouraged in the module body, use Application.compile_env/3 instead
  lib/auth_plug.ex:22: AuthPlug
```

Should be a easy/quick fix. 💭

### PR DESCRIPTION
**Pull request by nelsonic**
This PR: 
+ [x] downgrades the `plug` version requirement for maximum compatibility #76 
+ [x] chore: replace `Application.get_env/2` with `Application.compile_env/3` fixes #82

### CODE REVIEW

**Comment by nelsonic** [comment]
Package published to https://hex.pm/packages/auth_plug/1.4.18

**Comment by nelsonic** [comment]
Package published to https://hex.pm/packages/auth_plug/1.4.19 📦 
This is beyond a joke now ... 🤦‍♂️

**Comment by nelsonic** [comment]
Package published to https://hex.pm/packages/auth_plug/1.4.20 📦 
Loving this so much! 🙌 🙄

**Comment by nelsonic** [comment]
@nelsonic this is working in `auth`, `rbac`, etc.
Please review + merge. Thanks. 👌

**Comment by nelsonic** [comment]
Hi @SimonLab 👋 
Please review + merge when you can. 🙏  
(Thanks! 😊)

**Review by SimonLab — APPROVED** [review]
:+1:

**Pull request merged**
