### PR TITLE
Manage post request error

### PR DESCRIPTION
**Pull request by SimonLab**
Add condition to check errors on post requests for end session

see #38

### CODE REVIEW

**Comment by SimonLab** [comment]
Codecov is not updating the report, however this should now be at 100%
image

**Review by LuchoTurtle — DISMISSED** [review]
To me (as much as that's worth lmao) it looks awesome.
I was checking whether the `response` parameter in `parse_body_response` would ever be an empty object but according to HTTPoison's docs, doesn't seem to be the case.  🎉

**Review by nelsonic — APPROVED** [review]
Error handling looks great. Thanks very much @SimonLab 👍 
@LuchoTurtle always good to have your fresh eyes on this. 👌

**Comment by nelsonic** [comment]
Package published to https://hex.pm/packages/auth_plug/1.5.2 📦 contains this update. 🚀

**Pull request merged**
