### PR TITLE
Add a human readable error message when API key is not set

### LINKED ISSUE #19: Project doesn't compile without an API Key set
Mix fails to compile the project without an API key set due to the module attributes used in the Demo application. 

Is it possible to set these at runtime to avoid this and allow for some nicer error messages?

### PR DESCRIPTION
**Pull request by th0mas**
This helps to fix #19 

The demo app breaks during compilation without an API key, otherwise this error will appear on a human readable error page in Phoenix.

In compilation the error gets shown like this:
```
== Compilation error in file lib/demo/router.ex ==
** (RuntimeError) No AUTH_API_KEY set, find out how at https://github.com/dwyl/auth_plug#2-get-your-auth_api_key-
    lib/helpers.ex:33: AuthPlug.Helpers.check_environment_vars/0
    lib/auth_plug.ex:19: AuthPlug.init/1
    lib/plug/builder.ex:304: Plug.Builder.init_module_plug/4
    lib/plug/builder.ex:288: anonymous fn/5 in Plug.Builder.compile/3
    (elixir 1.10.3) lib/enum.ex:2111: Enum."-reduce/3-lists^foldl/2-0-"/3
    lib/plug/builder.ex:286: Plug.Builder.compile/3
    expanding macro: Plug.Builder.__before_compile__/1
    lib/demo/router.ex:1: AuthPlug.Router (module)
```

Which I still think is a big improvement over obscure pattern matching errors

### CODE REVIEW

**Comment by th0mas** [comment]
Testing this will be difficult as we'd have to mock not having the AUTH_API_KEY environment variable set

**Comment by nelsonic** [comment]
@th0mas we can _unset_ the Environment Variable at the start of the test 
and then set it again at the end of the test.
See: 
https://github.com/dwyl/auth_plug/blob/b612845c62d7257c4a665f83faea3c31debacbbf/test/token_test.exs#L31

**Comment by nelsonic** [comment]
@th0mas I tried to checkout this branch to add the test to bump back up to 100%:
image
The branch is on your fork: https://github.com/th0mas/auth_plug/tree/refractor

If you change the Git remote URL on your `localhost` to this repo: 
```
git remote set-url origin git@github.com:dwyl/auth_plug.git
```
You can push your branch to the dwyl repo.

You have direct write access:
image
So you shouldn't have any issues.

I'm happy to write the test if I have access to the branch.

**Comment by th0mas** [comment]
Pushed my changes to this repo under `refractor`. I also think you have edit to the `refractor` branch on my fork if that's an easier workflow - I'm not sure what the best "git magic" is in this situation

**Comment by nelsonic** [comment]
I think that due to how Travis CI handles hidden/encrypted environment variables it might be tricky to work on a Fork. 
But I will try that route first so that we can use this PR. And if it doesn't work, I will switch to the `dwyl:refractor` branch and we can create a new PR. 👍

**Comment by nelsonic** [comment]
Added test with clarifying comments:
https://github.com/dwyl/auth_plug/blob/7216b9f756cbadff4383b93df9a92568df9adc7e/test/helpers_test.exs#L23-L38

@th0mas thanks again for adding this check. It makes it a lot more friendly. 👍

**Comment by nelsonic** [comment]
Package published to https://hex.pm/packages/auth_plug/1.2.1

**Pull request merged**
